In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('50_Startups.csv')
print(dataset)
# xMtrx = dataset.iloc[:, :-1].values
# yVctr = dataset.iloc[:, -1].values

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

In [11]:
print(xMtrx)
print(yVctr)
print(type(yVctr))

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
<class 'numpy.ndarray'>


### Augmenting Missing Values

In [5]:
from sklearn.impute import SimpleImputer

independentNumVars = range(1, 3)
meanAugmenter = SimpleImputer(missing_values = np.nan, strategy = "mean")
meanAugmenter.fit(xMtrx[:, independentNumVars])
xMtrxAugmented = xMtrx
xMtrxAugmented[:, independentNumVars] = meanAugmenter.transform(xMtrx[:, independentNumVars])
print(xMtrxAugmented)

### Transforming categorical data

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columnsWithCategoricalData = [0]
categoricalTransformer = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), columnsWithCategoricalData)],
    remainder = 'passthrough')
xMtrx3 = categoricalTransformer.fit_transform(xMtrxAugmented)
print(xMtrx3)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Labeling (converting strings to number tags)

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
yLabeledVctr = encoder.fit_transform(yVctr)

### Splitting to train and test sets

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    xMtrx3, yLabeledVctr, test_size = 0.2, random_state = 1)
print(xMtrx3)
print(yLabeledVctr)
print("---")
print(x_train)
print(y_train)
print("---")
print(x_test)
print(y_test)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
---
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[0 1 0 0 1 1 0 1]
---
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1]


### Scaling (standardizing)

In [1]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
to_scale = x_train[:, 3:5]
x_train[:, 3:5] = scaler.fit_transform(x_train[:, 3:5])
print(x_train)
print("---")

x_test[:, 3:5] = scaler.transform(x_test[:, 3:5])
print(x_test)

NameError: ignored

### Linear Regression Model

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plot

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state = 0)

plot.scatter(x_train, y_train, color = 'red')

from sklearn.linear_model import LinearRegression
rgrs = LinearRegression()
rgrs.fit(x_train, y_train)
# plot.plot(x_train, rgrs.predict(x_train), color = 'blue')
print(type(x_train))
print(rgrs.predict(pd.DataFrame({"YearsExperience": [10, 13]})))
plot.scatter(x_test, y_test, color = 'green')
plot.plot(x_test, rgrs.predict(x_test), color = 'black')
plot.title("Salary/Experience")

# Our model-equasion is y = b0 + b1*x
# b0 is called "y-intercept"
# b1 is called "slope coefficient"
print(rgrs.intercept_)
print(rgrs.coef_)

### Setting options for NumPy and Pandas    

In [ ]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.options.mode.copy_on_write = True
np.set_printoptions(precision=2, suppress=True)